import {expect,test,Page} from "@playwright/test";
import {mailLink} from "./mail";
async function setup(page:Page,category:string,suffix:string){
  async function post(path:string,data:unknown){const csrf=await (await page.request.get('/api/v1/auth/csrf')).json();const response=await page.request.post('/api/v1'+path,{data,headers:{[csrf.headerName]:csrf.token}});expect(response.ok(),path).toBe(true);return response.status()===204?null:response.json();}
  const email=`ops-${suffix}@example.test`,password="Operational safe password!";
  await post('/auth/signup',{name:"운영자",email,password});const link=new URL(await mailLink(email,"VERIFY"));
  await post('/auth/email-verification/confirm',{token:new URLSearchParams(link.hash.slice(1)).get('token')});await post('/auth/login',{email,password});
  const studio=await post('/studios',{name:"운영 테스트",slug:`ops-${suffix}`,timezone:"Asia/Seoul"});
  await post(`/studios/${studio.id}/onboarding/complete`,{version:0,businessCategory:category,businessType:category==="LESSON"?"DANCE":"NAIL",
    capabilities:category==="LESSON"?{PRIVATE_LESSON:true,GROUP_CLASS:true,ATTENDANCE:true,PASS_MANAGEMENT:true,CUSTOMER_BOOKING:false}:{CUSTOMER_BOOKING:false,DEPOSIT:false,REVISIT:false},
    businessHours:Array.from({length:7},(_,i)=>({weekday:i+1,closed:false,openTime:"08:00",closeTime:"22:00"})),bookingPolicy:{slotIntervalMinutes:30,bookingWindowDays:30,cancellationCutoffHours:12},
    lessonPolicy:category==="LESSON"?{lowBalanceThreshold:2,expiryAlertDays:7,restoreOnTimelyCancellation:true}:null,beautyPolicy:category==="BEAUTY"?{depositEnabled:false,noShowEnabled:true}:null});
}
test('LESSON product enrollment private deduction renewal group attendance and cancellation',async({page},info)=>{
 test.setTimeout(240000);await setup(page,'LESSON',`lesson-${info.project.name}-${Date.now()}`);
 await page.goto('/app/customers/new');await page.getByLabel('이름',{exact:true}).fill('레슨 회원');await page.getByLabel('전화번호',{exact:true}).fill('010-1111-2222');await page.getByRole('button',{name:'회원 저장',exact:true}).click();await expect(page).toHaveURL(/\/customers\/[0-9a-f-]+$/);const customerUrl=page.url();
 async function product(name:string,trigger:string){await page.goto('/app/lesson/pass-products');await page.getByRole('button',{name:'이용권 만들기',exact:true}).click();await page.getByLabel('상품명',{exact:true}).fill(name);await page.getByLabel('구매 회차',{exact:true}).fill('10');await page.getByLabel('유효 일수 (선택)',{exact:true}).fill('30');await page.getByLabel('가격 (원)',{exact:true}).fill('100000');if(trigger!=="LESSON_COMPLETED")await page.locator('form.auth-form select').nth(1).selectOption(trigger);await page.getByRole('button',{name:'상품 저장',exact:true}).click();await expect(page.getByText(`${name} · 10회 · 100,000원 · 판매 중`,{exact:true})).toBeVisible();}
 await product('개인 10회','LESSON_COMPLETED');
 await page.goto(customerUrl);await page.getByRole('button',{name:'수강 추가',exact:true}).click();await expect(page.getByRole('heading',{name:'이용권 결제 확인',exact:true})).toBeVisible();
 async function buy(name:string){await page.getByRole('combobox',{name:'구매할 이용권',exact:true}).selectOption({label:`${name} · 100,000원`});await page.getByRole('button',{name:'수납 확인 · 이용 시작',exact:true}).click();}
 await buy('개인 10회');await expect(page.getByText('구매 10회 · 잔여 10회 · 예약 중 0회 · 예약 가능 10회',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'수업 일정',exact:true}).click();const date=new Date(Date.now()+2*86400000).toISOString().slice(0,10);await page.getByLabel('예약 날짜',{exact:true}).fill(date);
 async function privateBooking(start:string,end:string){await page.getByRole('button',{name:'개인 레슨 예약',exact:true}).click();await expect(page.getByRole('option',{name:'레슨 회원 · 010-1111-2222',exact:true})).toHaveCount(1);await page.getByRole('combobox',{name:'회원 선택',exact:true}).selectOption({label:'레슨 회원 · 010-1111-2222'});await expect(page.getByRole('option',{name:/개인 10회 · 예약 가능/})).toHaveCount(1);await page.getByRole('combobox',{name:'사용할 이용권',exact:true}).selectOption({index:1});await page.getByLabel('시작 시간',{exact:true}).fill(start);await page.getByLabel('종료 시간',{exact:true}).fill(end);await page.getByRole('button',{name:'예약 저장',exact:true}).click();await expect(page.getByRole('heading',{name:'개인 레슨 예약',exact:true})).toHaveCount(0);}
 await privateBooking('10:00','11:00');await page.getByRole('button',{name:'완료 처리',exact:true}).click();await expect(page.locator('.booking-item').getByText('완료',{exact:true})).toBeVisible();
 await privateBooking('12:00','13:00');await page.getByRole('button',{name:'예약 취소',exact:true}).click();await expect(page.locator('.booking-item').getByText('취소',{exact:true})).toBeVisible();
 await page.goto(customerUrl);await page.getByRole('combobox',{name:'수강 이력',exact:true}).selectOption({index:1});await expect(page.getByText('구매 10회 · 잔여 9회 · 예약 중 0회 · 예약 가능 9회',{exact:true})).toBeVisible();
 await buy('개인 10회');await expect(page.getByRole('heading',{name:'개인 10회 · 다음 이용 대기',exact:true})).toBeVisible();
 const old=page.locator('article').filter({has:page.getByRole('heading',{name:'개인 10회 · 이용 중',exact:true})});await old.getByRole('button',{name:'사용 이력 보기',exact:true}).click();await page.getByLabel('회차 조정',{exact:true}).fill('-9');await page.getByLabel('조정 사유',{exact:true}).fill('잔여 사용 정산');await page.getByRole('button',{name:'조정 기록',exact:true}).click();await expect(page.getByRole('heading',{name:'개인 10회 · 사용 완료',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'개인 10회 · 이용 중',exact:true})).toBeVisible();
 await product('그룹 10회','ATTENDANCE_PRESENT');
 await page.goto('/app/lesson/classes');await page.getByLabel('반 이름',{exact:true}).fill('그룹 A');await page.getByLabel('정원',{exact:true}).fill('5');await page.getByRole('combobox',{name:'담당 강사',exact:true}).selectOption({label:'운영자'});await page.getByRole('button',{name:'반 저장',exact:true}).click();await expect(page.getByRole('heading',{name:'반복 일정',exact:true})).toBeVisible();
 const later=new Date(Date.now()+4*86400000);const weekdayName=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',weekday:'short'}).format(later);const weekdays:Record<string,number>={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};const weekday=weekdays[weekdayName];
 await page.getByRole('combobox',{name:'수업 요일',exact:true}).selectOption(String(weekday));await page.getByLabel('수업 시작',{exact:true}).fill('16:00');await page.getByLabel('수업 시간 (분)',{exact:true}).fill('60');await page.getByRole('button',{name:'반복 일정 저장',exact:true}).click();await expect(page.getByRole('button',{name:'일정 수정',exact:true})).toHaveCount(1);
 await page.goto(customerUrl);await page.getByRole('combobox',{name:'수강 형태',exact:true}).selectOption('GROUP');await page.getByRole('combobox',{name:'등록할 반',exact:true}).selectOption({label:'그룹 A'});await page.getByRole('button',{name:'수강 추가',exact:true}).click();await expect(page.getByRole('heading',{name:'이용권 결제 확인',exact:true})).toBeVisible();await buy('그룹 10회');await expect(page.getByRole('heading',{name:'그룹 10회 · 이용 중',exact:true})).toBeVisible();
 await page.goto('/app/lesson/attendance');await page.getByRole('combobox',{name:'반 선택',exact:true}).selectOption({label:'그룹 A'});await page.getByLabel('수업 월',{exact:true}).fill(later.toISOString().slice(0,7));await page.getByRole('button',{name:'회차 선택',exact:true}).first().click();
 await page.getByRole('combobox',{name:'회원 선택',exact:true}).selectOption({label:'레슨 회원 · 010-1111-2222'});await expect(page.getByRole('option',{name:/그룹 10회 · 예약 가능/})).toHaveCount(1);await page.getByRole('combobox',{name:'사용할 이용권',exact:true}).selectOption({index:1});await page.getByRole('button',{name:'그룹 예약 추가',exact:true}).click();await expect(page.getByText('잔여 10회 · 예약 가능 9회',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'현재 페이지 전체 출석',exact:true}).check();await page.getByRole('button',{name:'출석 일괄 저장',exact:true}).click();await expect(page.getByText('잔여 9회 · 예약 가능 9회',{exact:true})).toBeVisible();await page.reload();await page.getByRole('combobox',{name:'반 선택',exact:true}).selectOption({label:'그룹 A'});await page.getByRole('button',{name:'회차 선택',exact:true}).first().click();await expect(page.getByText('잔여 9회 · 예약 가능 9회',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>localStorage.length)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
